export const IMDB_RESULTS = 'IMDB_RESULTS';
export const RESET_IMDB_RESULTS = 'RESET_IMDB_RESULTS';
export const FIRST_THING_CHOSEN = 'FIRST_THING_CHOSEN';
export const RESET_FIRST_THING = 'RESET_FIRST_THING';
export const SECOND_THING_CHOSEN = 'SECOND_THING_CHOSEN';
export const RESET_SECOND_THING = 'RESET_SECOND_THING';
export const EDIT_FIRST_THING = 'EDIT_FIRST_THING';
export const EDIT_SECOND_THING = 'EDIT_SECOND_THING';
